import { jsPDF } from "jspdf";
import { autoTable } from "jspdf-autotable";
import QRCode from "qrcode";
import { format, isValid } from "date-fns";

const COMPANY = {
  name: "DEVIONIC (PRIVATE) LIMITED",
  system: "DEVIONIC DIGITAL DATABASE & REGISTRATION SYSTEM",
  office: "GENERATED BY DEVIONIC (PRIVATE) LIMITED HEADOFFICE",
  website: "www.devionic.com",
  address: "Head Office-Devionic Multan Road Chowk Azam, Tehsil & District Layyah, Punjab, Pakistan Postal Code 31450",
  phone: "+92-317-7121841",
  email: "info@devionic.com",
};

// A4 dimensions in mm
export const A4_WIDTH = 210;
export const A4_HEIGHT = 297;
// Thin border margin (approx 1px at 72dpi ≈ 0.35mm, use 2mm for visibility)
const BORDER_MARGIN = 2;
const CONTENT_MARGIN = 10;

// Document type prefixes
export type DocType = "JOB" | "EMP" | "INV" | "QUO" | "SAL" | "HO";

// Safe Date Formatting
export const formatDateSafe = (date: any, formatStr: string = "dd/MM/yyyy") => {
  try {
    if (!date) return "N/A";
    const d = new Date(date);
    if (!isValid(d)) return "N/A";
    return format(d, formatStr);
  } catch {
    return "N/A";
  }
};

// Safe Items Parsing
export const parseItems = (items: any): any[] => {
  if (!items) return [];
  if (Array.isArray(items)) return items;
  if (typeof items === "string") {
    try {
      const parsed = JSON.parse(items);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }
  return [];
};

// Generate document number in format: DEV-DDMMYYYY-TYPE-XXXX
export const generateDocNumber = (seq: number = 1, type: DocType = "HO"): string => {
  const now = new Date();
  const dateStr = `${String(now.getDate()).padStart(2, "0")}${String(now.getMonth() + 1).padStart(2, "0")}${now.getFullYear()}`;
  return `DEV-${dateStr}-${type}-${String(seq).padStart(4, "0")}`;
};

// Draw a barcode-like pattern (black bars on white)
const drawBarcode = (doc: jsPDF, text: string, x: number, y: number, width: number, height: number) => {
  const hash = text.split("").reduce((a, c) => a + c.charCodeAt(0), 0);
  let currentX = x;
  const numBars = Math.floor(width / 1.5);

  for (let i = 0; i < numBars; i++) {
    const isThick = ((hash * (i + 1)) % 3) !== 0;
    const w = isThick ? 1.0 : 0.5;
    const show = ((hash * (i + 1)) % 5) !== 0;
    if (show) {
      doc.setFillColor(0, 0, 0);
      doc.rect(currentX, y, w, height, "F");
    }
    currentX += 1.5;
  }

  doc.setFontSize(7);
  doc.setTextColor(0, 0, 0);
  doc.text(String(text), x + width / 2, y + height + 4, { align: "center" });
};

// Load icon logo as base64
let iconLogoCache: string | null = null;

const loadIconLogo = async (): Promise<string | null> => {
  if (iconLogoCache) return iconLogoCache;
  try {
    const logoModule = await import("@/assets/devionic-icon.png");
    const logoUrl = logoModule.default || logoModule;
    return new Promise((resolve) => {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => {
        try {
          const canvas = document.createElement("canvas");
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext("2d");
          ctx?.drawImage(img, 0, 0);
          iconLogoCache = canvas.toDataURL("image/png");
          resolve(iconLogoCache);
        } catch {
          resolve(null);
        }
      };
      img.onerror = () => resolve(null);
      img.src = logoUrl;
    });
  } catch {
    return null;
  }
};

// Load full logo as base64
let fullLogoCache: string | null = null;

const loadFullLogo = async (): Promise<string | null> => {
  if (fullLogoCache) return fullLogoCache;
  try {
    const logoModule = await import("@/assets/devionic-logo.png");
    const logoUrl = logoModule.default || logoModule;
    return new Promise((resolve) => {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => {
        try {
          const canvas = document.createElement("canvas");
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext("2d");
          ctx?.drawImage(img, 0, 0);
          fullLogoCache = canvas.toDataURL("image/png");
          resolve(fullLogoCache);
        } catch {
          resolve(null);
        }
      };
      img.onerror = () => resolve(null);
      img.src = logoUrl;
    });
  } catch {
    return null;
  }
};

// Generate a real scannable QR code as base64 data URL
const generateQrBase64 = async (url: string): Promise<string | null> => {
  try {
    const dataUrl = await QRCode.toDataURL(url, {
      width: 200,
      margin: 1,
      errorCorrectionLevel: "M",
      color: { dark: "#000000", light: "#ffffff" },
    });
    return dataUrl;
  } catch {
    return null;
  }
};

/**
 * Draw a thin 1px border around the entire page
 */
export const addPageBorder = (doc: jsPDF) => {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.3);
  doc.rect(BORDER_MARGIN, BORDER_MARGIN, w - BORDER_MARGIN * 2, h - BORDER_MARGIN * 2);
};

/**
 * PDF Header:
 * LEFT: D icon logo + 3 lines text
 * RIGHT: Barcode with doc number
 * Thin line separator below
 */
export const addPdfHeader = async (
  doc: jsPDF,
  docNumber: string,
  options?: { title?: string; verifyUrl?: string }
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = CONTENT_MARGIN;
  const headerY = BORDER_MARGIN + 5;

  // Draw page border
  addPageBorder(doc);

  // LEFT: Logo icon
  const logo = await loadIconLogo();
  let textStartX = margin;

  if (logo) {
    try {
      const logoSize = 18;
      doc.addImage(logo, "PNG", margin, headerY - 2, logoSize, logoSize);
      textStartX = margin + logoSize + 4;
    } catch { /* skip */ }
  }

  // LEFT: 3 lines of text next to logo
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");
  doc.text(COMPANY.name, textStartX, headerY + 3);

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(COMPANY.system, textStartX, headerY + 9);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(COMPANY.office, textStartX, headerY + 14);

  // RIGHT: Barcode with doc number
  const barcodeWidth = 50;
  const barcodeX = pageWidth - margin - barcodeWidth;
  drawBarcode(doc, docNumber, barcodeX, headerY - 1, barcodeWidth, 14);

  // Thin separator line below header
  const lineY = headerY + 19;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, lineY, pageWidth - margin, lineY);

  // Document title below separator
  const contentStart = lineY + 5;
  if (options?.title) {
    doc.setFontSize(14);
    doc.setTextColor(13, 27, 42);
    doc.setFont("helvetica", "bold");
    doc.text(String(options.title), pageWidth / 2, contentStart + 5, { align: "center" });
  }

  // Reset
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "normal");

  return options?.title ? contentStart + 12 : contentStart;
};

/**
 * PDF Footer:
 * QR code bottom-right above text (real scannable)
 * Cyan separator line
 * Line 1: Verification ID | Date & Time | Verified on devionic.com
 * Line 2: Phone | Email | Website | Address
 */
export const addPdfFooter = async (
  doc: jsPDF,
  verificationId: string,
  verifyUrl: string
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = CONTENT_MARGIN;

  // QR Code - bottom right, above footer text (real scannable)
  const qrSize = 18;
  const qrY = pageHeight - BORDER_MARGIN - 42;
  try {
    const qrBase64 = await generateQrBase64(verifyUrl);
    if (qrBase64) {
      doc.addImage(qrBase64, "PNG", pageWidth - margin - qrSize, qrY, qrSize, qrSize);
    }
  } catch { /* skip */ }

  // Cyan separator line
  const footerY = pageHeight - BORDER_MARGIN - 20;
  doc.setDrawColor(0, 186, 199);
  doc.setLineWidth(0.8);
  doc.line(margin, footerY, pageWidth - margin, footerY);

  const now = new Date();
  const dateTime = now.toLocaleString("en-US", {
    year: "numeric", month: "short", day: "numeric",
    hour: "2-digit", minute: "2-digit", second: "2-digit",
  });

  // Line 1: Verification ID | Date & Time | Verified on devionic.com
  doc.setFontSize(7);
  doc.setTextColor(80, 80, 80);
  const line1 = `Verification ID: ${verificationId}    |    Date & Time: ${dateTime}    |    Verified on devionic.com`;
  doc.text(line1, pageWidth / 2, footerY + 6, { align: "center" });

  // Line 2: Phone | Email | Website | Address
  const line2 = `${COMPANY.phone}  |  ${COMPANY.email}  |  ${COMPANY.website}  |  ${COMPANY.address}`;
  doc.text(line2, pageWidth / 2, footerY + 11, { align: "center" });
};

/**
 * Custom PDF Header for Applications:
 * LEFT: QR Code (real scannable)
 * CENTER: Devionic Logo + "APPLICATION FOR EMPLOYMENT"
 * RIGHT: Applicant Passport Photo
 */
export const addApplicationHeader = async (
  doc: jsPDF,
  verificationId: string,
  verifyUrl: string,
  title?: string,
  photoUrl?: string
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = CONTENT_MARGIN;
  const headerY = BORDER_MARGIN + 5;

  // 1. LEFT: QR Code
  const qrSize = 18;
  try {
    const qrBase64 = await generateQrBase64(verifyUrl);
    if (qrBase64) {
      doc.addImage(qrBase64, "PNG", margin, headerY - 1, qrSize, qrSize);
    }
  } catch { /* skip */ }

  // 2. CENTER: Logo + Title
  const fullLogo = await loadFullLogo();
  if (fullLogo) {
    try {
      const logoW = 42;
      const logoH = 10; 
      doc.addImage(fullLogo, "PNG", (pageWidth / 2) - (logoW / 2), headerY + 1.5, logoW, logoH);
      
      if (title) {
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(13, 27, 42);
        // Added 8.5mm gap between logo bottom and title for professional branding
        doc.text(String(title).toUpperCase(), pageWidth / 2, headerY + 20, { align: "center" });
      }
    } catch { /* skip */ }
  } else if (title) {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(13, 27, 42);
    doc.text(String(title).toUpperCase(), pageWidth / 2, headerY + 10, { align: "center" });
  }

  // 3. RIGHT: Applicant Photo
  if (photoUrl) {
    try {
      const photoW = 22;
      const photoH = 26;
      doc.setFillColor(248, 248, 248);
      doc.setDrawColor(220, 220, 220);
      doc.rect(pageWidth - margin - photoW, headerY, photoW, photoH, "FD");
      doc.addImage(photoUrl, "JPEG", pageWidth - margin - photoW + 0.5, headerY + 0.5, photoW - 1, photoH - 1);
    } catch { 
      // Fallback
    }
  } else {
    // Empty photo box
    const photoW = 20;
    const photoH = 25;
    doc.setDrawColor(200, 200, 200);
    doc.rect(pageWidth - margin - photoW, headerY, photoW, photoH);
    doc.setFontSize(6);
    doc.setTextColor(150, 150, 150);
    doc.text("PASTE PHOTO", pageWidth - margin - photoW/2, headerY + photoH/2, { align: "center" });
  }

  // Final Header Formatting
  const lineY = headerY + 30;
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.4);
  doc.line(margin, lineY, pageWidth - margin, lineY);

  return lineY + 6;
};

/**
 * Custom PDF Footer for Applications:
 * CENTER: Computerized Document Text
 */
export const addApplicationFooter = async (
  doc: jsPDF,
  verificationId: string,
  verifyUrl: string
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = CONTENT_MARGIN;
  const footerY = pageHeight - BORDER_MARGIN - 20;

  // 1. Cyan separator line
  doc.setDrawColor(0, 186, 199);
  doc.setLineWidth(0.6);
  doc.line(margin, footerY, pageWidth - margin, footerY);

  // 2. CENTER: Computerized Text
  doc.setFontSize(7.5);
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "normal");
  
  const line1 = "This is computerized generated document generated by Devionic (Private) Limited";
  const line2 = "+92-317-7121841 | info@devionic.com | www.devionic.com | Head Office-Devionic Multan Road Chowk Azam, Tehsil & District Layyah, Punjab, Pakistan Postal Code 31450";
  
  doc.text(line1, pageWidth / 2, footerY + 6, { align: "center" });
  doc.setFontSize(7);
  doc.text(line2, pageWidth / 2, footerY + 11, { align: "center" });
};

/**
 * Add border to all pages of a multi-page document
 */
export const addBorderToAllPages = (doc: jsPDF) => {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addPageBorder(doc);
  }
};

// ===== HTML Print Template =====

// Load icon as base64 for HTML templates
let htmlIconCache: string | null = null;
const loadHtmlIcon = async (): Promise<string> => {
  if (htmlIconCache) return htmlIconCache;
  try {
    const mod = await import("@/assets/devionic-icon.png");
    return new Promise((resolve) => {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => {
        const c = document.createElement("canvas");
        c.width = img.width; c.height = img.height;
        c.getContext("2d")?.drawImage(img, 0, 0);
        htmlIconCache = c.toDataURL("image/png");
        resolve(htmlIconCache);
      };
      img.onerror = () => resolve("");
      img.src = mod.default;
    });
  } catch { return ""; }
};

export const getHtmlPrintHeader = async (docNumber: string, verifyUrl?: string): Promise<string> => {
  const iconBase64 = await loadHtmlIcon();

  return `
  <div style="display:flex;align-items:center;justify-content:space-between;padding:4px 8px;">
    <div style="display:flex;align-items:center;gap:10px;">
      ${iconBase64 ? `<img src="${iconBase64}" width="40" height="40" style="object-fit:contain;" />` : `<div style="width:40px;height:40px;background:#0d1b2a;border-radius:6px;display:flex;align-items:center;justify-content:center;color:#00bac7;font-size:24px;font-weight:bold;">D</div>`}
      <div>
        <div style="font-size:8px;color:#333;letter-spacing:0.5px;">${COMPANY.name}</div>
        <div style="font-size:10px;font-weight:bold;color:#000;letter-spacing:0.3px;">${COMPANY.system}</div>
        <div style="font-size:8px;color:#333;">${COMPANY.office}</div>
      </div>
    </div>
    <div style="text-align:right;">
      <div style="font-family:'Libre Barcode 39',monospace;font-size:32px;letter-spacing:2px;">${docNumber}</div>
      <div style="font-size:7px;color:#555;text-align:center;">${docNumber}</div>
    </div>
  </div>
  <div style="height:1px;background:#ccc;margin:0 8px 10px 8px;"></div>
`;
};

export const getHtmlPrintFooter = (verificationId: string, verifyUrl: string): string => {
  const now = new Date();
  const dateTime = now.toLocaleString("en-US", {
    year: "numeric", month: "short", day: "numeric",
    hour: "2-digit", minute: "2-digit", second: "2-digit",
  });

  const qrUrl = verifyUrl ? `https://api.qrserver.com/v1/create-qr-code/?size=80x80&data=${encodeURIComponent(verifyUrl)}` : "";

  return `
    ${qrUrl ? `<div style="text-align:right;padding:8px 8px 4px;"><img src="${qrUrl}" width="50" height="50" style="display:inline-block;" /></div>` : ""}
    </div>
    <div style="margin-top:4px;border-top:2px solid #00bac7;padding-top:6px;font-size:8px;color:#555;text-align:center;margin-left:8px;margin-right:8px;">
      <div>Verification ID: <span style="color:#00bac7;">${verificationId}</span> &nbsp;&nbsp;|&nbsp;&nbsp; Date &amp; Time: <span style="color:#00bac7;">${formatDateSafe(new Date(), "PPpp")}</span> &nbsp;&nbsp;|&nbsp;&nbsp; Verified on <span style="color:#00bac7;">devionic.com</span></div>
      <div style="margin-top:3px;">${COMPANY.phone} &nbsp;|&nbsp; ${COMPANY.email} &nbsp;|&nbsp; ${COMPANY.website} &nbsp;|&nbsp; ${COMPANY.address}</div>
    </div>
  `;
};

export const getHtmlPrintStyles = (): string => `
  @import url('https://fonts.googleapis.com/css2?family=Libre+Barcode+39&display=swap');
  body { font-family: Arial, sans-serif; padding: 0; margin: 0; color: #333; }
  @page { size: A4; margin: 2mm; }
  .page-wrapper { border: 0.3px solid #bbb; min-height: 100%; padding: 0; box-sizing: border-box; }
  .content { padding: 10px 20px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; }
  th { background: #f8f8f8; font-weight: 600; }
  .total-row { font-weight: bold; font-size: 18px; }
  @media print { body { padding: 0; } }
`;
