ALTER TABLE profiles ADD INDEX idx_profiles_created_at (created_at);
ALTER TABLE profiles ADD INDEX idx_profiles_approved_rejected (is_approved, is_rejected, created_at);
ALTER TABLE customers ADD INDEX idx_customers_created_at (created_at);
ALTER TABLE staff ADD INDEX idx_staff_name_active (is_active, name);
ALTER TABLE staff ADD INDEX idx_staff_department_join_date (department, join_date);
ALTER TABLE projects ADD INDEX idx_projects_client_email_created_at (client_email, created_at);
ALTER TABLE projects ADD INDEX idx_projects_status_created_at (status, created_at);
ALTER TABLE invoices ADD INDEX idx_invoices_client_email_created_at (client_email, created_at);
ALTER TABLE invoices ADD INDEX idx_invoices_status_created_at (status, created_at);
ALTER TABLE quotations ADD INDEX idx_quotations_client_email_created_at (client_email, created_at);
ALTER TABLE quotations ADD INDEX idx_quotations_status_created_at (status, created_at);
ALTER TABLE quote_requests ADD INDEX idx_quote_requests_status_created_at (status, created_at);
ALTER TABLE quote_requests ADD INDEX idx_quote_requests_email_created_at (email, created_at);
ALTER TABLE inquiries ADD INDEX idx_inquiries_status_read_created_at (status, is_read, created_at);
ALTER TABLE inquiries ADD INDEX idx_inquiries_email_created_at (email, created_at);
ALTER TABLE service_inquiries ADD INDEX idx_service_inquiries_status_read_created_at (status, is_read, created_at);
ALTER TABLE service_inquiries ADD INDEX idx_service_inquiries_email_created_at (email, created_at);
ALTER TABLE complaints ADD INDEX idx_complaints_status_created_at (status, created_at);
ALTER TABLE complaints ADD INDEX idx_complaints_tracking_id (tracking_id);
ALTER TABLE tickets ADD INDEX idx_tickets_status_created_at (status, created_at);
ALTER TABLE tickets ADD INDEX idx_tickets_tracking_id (tracking_id);
ALTER TABLE complaint_notes ADD INDEX idx_complaint_notes_complaint_created_at (complaint_id, created_at);
ALTER TABLE ticket_notes ADD INDEX idx_ticket_notes_ticket_created_at (ticket_id, created_at);
ALTER TABLE inquiry_notes ADD INDEX idx_inquiry_notes_inquiry_created_at (inquiry_id, created_at);
ALTER TABLE quote_request_notes ADD INDEX idx_quote_request_notes_quote_created_at (quote_request_id, created_at);
ALTER TABLE testimonials ADD INDEX idx_testimonials_approved_active_created_at (is_active, is_approved, created_at);
ALTER TABLE financials ADD INDEX idx_financials_entry_date_type (entry_date, type);
ALTER TABLE transactions ADD INDEX idx_transactions_date_type (transaction_date, type);
ALTER TABLE transactions ADD INDEX idx_transactions_display_id (display_id);
ALTER TABLE services ADD INDEX idx_services_active_sort_order (is_active, sort_order);
ALTER TABLE jobs ADD INDEX idx_jobs_active_created_at (is_active, created_at);
ALTER TABLE job_applications ADD INDEX idx_job_applications_job_status_created_at (job_id, status, created_at);
ALTER TABLE job_applications ADD INDEX idx_job_applications_email_created_at (email, created_at);
ALTER TABLE attendance ADD INDEX idx_attendance_staff_date (staff_id, date);
ALTER TABLE salary_slips ADD INDEX idx_salary_slips_staff_year_month (staff_id, year, month);
ALTER TABLE site_settings ADD INDEX idx_site_settings_key (`key`);
ALTER TABLE admin_notifications ADD INDEX idx_admin_notifications_read_created_at (is_read, created_at);
ALTER TABLE login_attempts ADD INDEX idx_login_attempts_email_ip_action_created_at (email, ip_address, action, created_at);
ALTER TABLE visitor_sessions ADD INDEX idx_visitor_sessions_session_id (session_id);
ALTER TABLE visitor_sessions ADD INDEX idx_visitor_sessions_online_last_seen (is_online, last_seen_at);
ALTER TABLE page_views ADD INDEX idx_page_views_session_created_at (session_id, created_at);
ALTER TABLE feedback_calls ADD INDEX idx_feedback_calls_created_at (created_at);
ALTER TABLE bookings ADD INDEX idx_bookings_status_created_at (status, created_at);
